fastlane_require "increment_semver"
fastlane_require "json"
fastlane_require "httparty"

actions_path 'actions/'
fastlane_version "2.61.0"
default_platform :android

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean test", build_type: "Release")
  end

  desc "Deploy the library. Available options: type:major|minor|patch optional: branch:YOUR_BRANCH (default master) notest:true|false (default false)"
  lane :deploy do |options|
    # Arguments handling
    branch = options[:branch] || "master"
    notest = options[:notest] || false
    type = options[:type]
    UI.user_error!("You need to specify a type.") unless type != nil
    UI.user_error!("Type #{type} is not a valid type (patch/minor/major") unless ["major","minor","patch"].include? type

    # Compute next version number
    current_version = get_version_name(
      gradle_file_path:"algoliasearch/common.gradle",
      ext_constant_name:"PUBLISH_VERSION"
    ).tr("'", "")
    puts "Current version: #{current_version}"
    version_number = increment_semver(current_version, type)
    puts "New version: #{version_number}"

    # Ensure branch is master & WC clean, then pull changes
    git checkout Gemfile.lock # Ignore different bundle version changing Gemfile https://discuss.bitrise.io/t/5176/5
    prepare_git()

    # Generate changelog updates
    changes = sh("conventional-changelog --preset angular --output-unreleased", log:false)
    changes_lines = changes.split(/\n+/)[2..-1] # Remove header
    changes_lines[0] = "## #{version_number}"
    changes = changes_lines.join("\n")
    puts "Changes: #{changes}"
    file_edit("../CHANGELOG.md", /^(# Changelog\n+)/, "\\1\n#{changes}\n")

    # Tests / deployment
    if notest == false
        test()
    end

    masterHash = sh("git rev-parse origin/master")
    headHash = sh("git rev-parse HEAD")
    if masterHash != headHash
      raise "Error: master and HEAD hashes do not match, meaning that we are probably not on master and therefore can't deploy"
    end

    # Release the new version
    sh("cd .. && ./release.sh #{version_number}")
    # Post the changes via GitHub Release API
    post_github_release(version_number, changes)
    # Remove temporary version tags
    sh("git tag --delete minor major patch | true")
    sh("git push origin :refs/tag/patch :refs/tag/minor :refs/tag/major")
  end
end

def prepare_git(ensure_clean=true)
  masterHash = sh("git rev-parse origin/master")
  headHash = sh("git rev-parse HEAD")

  if masterHash != headHash
    raise "Error: Master and Head Hashes do not match, meaning that we are probably not on Master and therefore can't deploy"
    #TODO: Does it make sense to checkout master if we raise error when HEAD != master?
  end
  sh("git checkout master")

  git_pull
  if ensure_clean
    ensure_git_status_clean(show_uncommitted_changes:true)
  end
end

def file_edit(filename, regexp, replacement)
  Tempfile.open(".#{File.basename(filename)}", File.dirname(filename)) do |tempfile|
    File.open(filename).each do |line|
      tempfile.puts line.gsub(regexp, replacement)
    end
    tempfile.fdatasync
    tempfile.close
    stat = File.stat(filename)
    FileUtils.chown stat.uid, stat.gid, tempfile.path
    FileUtils.chmod stat.mode, tempfile.path
    FileUtils.mv tempfile.path, filename
  end
end

def post_github_release(version, changes, token=ENV['GITHUB_TOKEN'])
  puts "Creating release on GitHub..."
  release_changes = changes.gsub(/^## #{version} /m, "## ").gsub("\n", "\\n")
  url = "https://api.github.com/repos/algolia/algoliasearch-client-android/releases?access_token=#{token}"
  result = HTTParty.post(url, :body => {
    :tag_name => version,
    :target_commitish => "master",
    :name => version,
    :body => release_changes,
    :draft => false,
    :prerelease => false}.to_json)
  puts "Release posted: #{result}."
end
